version: '3'

services:
  web:
    container_name: bun
    build: 
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in db container
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOSTNAME: db
      PORTGRES_PORT: 5432
      TZ: "Asia/Tokyo"
    volumes:
      - ..:/next-js-learn
    working_dir: /next-js-learn
    ports:
      - 3000:3000
    tty: true


  db:
    container_name: postgresdb
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../initdb:/docker-entrypoint-initdb.d
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in app container
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      TZ: "Asia/Tokyo"
    ports:
      - 15432:5432

volumes:
  postgres-data: